instruction: |
  Try to generate a proof for the following statement:
strict_parsing: false
n_problems: 50
date: "2026-05-01"
final_answer: false
dataset_path: MathArena/brokenarxiv-0526
judge_configs:
  - judges/arxiv_judge_post_march
