model: gpt-5.5--xhigh
api: openai
max_tokens: 128000
cache_read_cost: 0.5
read_cost: 5
write_cost: 30
concurrent_requests: 128
temperature: null
top_p: null
human_readable_id: GPT-5.5 (xhigh)
batch_processing: false
background: true
use_openai_responses_api: true
date: "2026-04-24"
service_tier: "flex"
reasoning:
  summary: "auto"
other_params:
  open: false
  creator: OpenAI