model: MathArena/qwen3.5-2b-arxivmath-sft
api: custom
api_key_env: VLLM_API_KEY
base_url: http://localhost:8004/v1
max_tokens: 81920
temperature: 1.0
top_p: 0.95
presence_penalty: 1.5
extra_body:
  top_k: 20
  min_p: 0.0
  repetition_penalty: 1.0
  chat_template_kwargs:
    enable_thinking: true
concurrent_requests: 64
read_cost: 0.0
write_cost: 0.0
human_readable_id: Qwen3.5-2B ArxivMath SFT
date: "2026-03-02"
other_params:
  open: false
  creator: MathArena
  parameters: 2.0
  active_parameters: 2.0
  huggingface_id: MathArena/qwen3.5-2b-arxivmath-sft
